language: go

go:
  - "1.14"
services:
  - docker
env:
  - GO111MODULE=on OPERATOR_VERSION=v0.17.0 BUILD_VERSION=${TRAVIS_TAG:-latest}
install:
  - curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_VERSION}/operator-sdk-${OPERATOR_VERSION}-x86_64-linux-gnu
  - chmod +x operator-sdk-${OPERATOR_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${OPERATOR_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${OPERATOR_VERSION}-x86_64-linux-gnu
  - operator-sdk version
script:
  - operator-sdk build devcsrj/gravitee-operator:$BUILD_VERSION --verbose
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  on:
    tags: true
  script: docker push devcsrj/gravitee-operator
